name: face_auth_engine
description: "A stateless face recognition engine for Flutter with ML Kit detection, landmark alignment, and MobileFaceNet embeddings."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.13.1
  image: ^4.6.0
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/models/mobilefacenet.tflite
